---
# tasks file for nginx_php
- name: Install nginx and php-fpm
  package:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - nginx
    - php-fpm
    - php
  become: yes

- name: Config nginx
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/default.d/nginx_php.conf
  notify: Reload nginx
  become: yes

- name: Create index.php
  copy:
    content: "<?php phpinfo(); ?>"
    dest: /var/www/html/index.php
    mode: 0777
  become: yes
