---
 - hosts: test
   gather_facts: no
   tasks:
    - name: install httpd
      yum:
       name: httpd
       state: installed

    - name: remove conf.d directory
      file:
       path: /etc/httpd/conf.d
       state: absent

    - name: creating conf.d directory
      file:
       path: /etc/httpd/conf.d
       state: directory

    - name: add new conf.d
      copy:
       src: /etc/ansible/playbooks/files/vhost.conf
       dest: /etc/httpd/host1.conf
       remote_src: yes  #на управляемой машине
      notify: restart_httpd

    - name: create htpasswd #шифрование
      command: 'htpasswd -b -c /etc/httpd/.htpasswd user1 12345'

    - name: create content
      copy:
       src: /etc/ansible/playbooks/files/content.html
       dest: /var/www/html/index.html
       remote_src: yes

   handlers:
   -name: restart httpd
   listen: restart httpd
   service:
   name: httpd
   state: restarted
