---
- name: Create user and set SSH key
  hosts: test
  become: yes
  tasks:
    - name: Create user1
      user:
        name: user1
        state: present
        shell: /bin/bash
        create_home: yes
        generate_ssh_key: yes
        ssh_key_bits: 2048
        ssh_key_file: .ssh/id_rsa

    - name: b64
      command: '/etc/ansible/playbooks/b64.sh'

    - name: Add encrypted SSH private key for user1
      copy:
        src: "/home/user1/.ssh/id_rsa_pub.b64"
        dest: "/home/user1/.ssh/id_rsa_pub.b64"
        remote src: yes
        mode: '0600'
        owner: user1
        group: user1

    - name: b64
      command: '/etc/ansible/playbooks/decode.sh'

